version: '2'
services:
  db:
    image: mysql:5.6
    expose:
      - "3306"
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: database_test
      MYSQL_USER: root
      MYSQL_PASSWORD: testpw
      MYSQL_ROOT_PASSWORD: testpw
  web:
    build: .
    command: npm test
    volumes:
      - .:/usr/maxwell-forms/
    depends_on:
      - db
    links:
      - db
    environment:
      NODE_ENV: test