version: '2'
services:
  db:
    image: mysql:5.6
    expose:
      - "3306"
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: database_development
      MYSQL_USER: root
      MYSQL_PASSWORD: testpw
      MYSQL_ROOT_PASSWORD: testpw
  web:
    build: .
    # only runs the application if unit tests pass
    command: node server.js
    volumes:
      - .:/usr/maxwell-forms/
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db
    environment:
      NODE_ENV: development